# Generated by Django 5.2.8 on 2025-12-11 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_course_average_rating"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="course",
            options={"ordering": ["-created_at"]},
        ),
    ]
